name: Build package

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  wait-dependencies:
    runs-on: ubuntu-slim
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Wait for dependencies
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        python3 package.py wait-dependencies


  build-linux-x86_64:
    runs-on: ubuntu-24.04
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install build requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential checkinstall libreadline-dev libgdbm-dev libssl-dev libsqlite3-dev tk-dev libncurses5-dev libffi-dev libreadline-dev libbz2-dev liblzma-dev zlib1g-dev git

    - name: Build python
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="linux-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV
        export BUILD_CPU_CORES=$(nproc)
        python3 package.py install-build-dependencies
        ./scripts/python/build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artifacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install build requirements
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential checkinstall libreadline-dev libgdbm-dev libssl-dev libsqlite3-dev tk-dev libncurses5-dev libffi-dev libreadline-dev libbz2-dev liblzma-dev zlib1g-dev git

    - name: Build python
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="linux-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV
        export BUILD_CPU_CORES=$(nproc)
        python3 package.py install-build-dependencies
        ./scripts/python/build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artifacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-win-arm64:
    runs-on: windows-11-vs2026-arm
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install v143 Toolset for ARM64
      run: |
        Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" `
        -ArgumentList "modify --installPath ""C:\Program Files\Microsoft Visual Studio\2026\Enterprise"" --add Microsoft.VisualStudio.Component.VC.14.44.17.14.ARM64 --quiet --norestart --wait" `
        -NoNewWindow -Wait

    - name: Setup MSVC developer command prompt
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: arm64
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    - name: Build python
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="win-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV
        python3 package.py install-build-dependencies
        ./scripts/python/build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artifacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-win-x86_64:
    runs-on: windows-2025-vs2026
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup MSVC developer command prompt
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    - name: Build python
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="win-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV
        python3 package.py install-build-dependencies
        ./scripts/python/build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artifacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-macos-arm64:
    runs-on: macos-15
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install build requirements
      shell: bash
      run: |
        brew install openssl xz gdbm cmake wget pkg-config

    - name: Build python
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="macos-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV
        export BUILD_CPU_CORES=$(sysctl -n hw.ncpu)
        python3 package.py install-build-dependencies
        ./scripts/python/build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artifacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-macos-x86_64:
    runs-on: macos-15-intel
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install build requirements
      shell: bash
      run: |
        brew trust aws/tap
        brew install openssl xz gdbm cmake wget pkg-config

    - name: Build python
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="macos-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV
        export BUILD_CPU_CORES=$(sysctl -n hw.ncpu)
        python3 package.py install-build-dependencies
        ./scripts/python/build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artifacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  wait-build-all:
    runs-on: ubuntu-24.04
    environment: build
    needs: [ build-linux-arm64, build-linux-x86_64, build-win-arm64, build-win-x86_64, build-macos-arm64, build-macos-x86_64 ]

    steps:
    - name: Wait for all platform builds to complete
      shell: bash
      run: |
        echo "done"

  release-linux-x86_64:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ wait-build-all ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="linux-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Download artefact
      uses: actions/download-artifact@v8
      with:
        name: python-${{env.BUILD_VERSION}}-linux-x86_64.tar.bz2

    - name: Upload release
      run: |
        gh release create "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" -n "release from pipeline" -t "v${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}" || true
        gh release upload "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" "python-${{env.BUILD_VERSION}}-linux-x86_64.tar.bz2" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-linux-arm64:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ wait-build-all ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="linux-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Download artefact
      uses: actions/download-artifact@v8
      with:
        name: python-${{env.BUILD_VERSION}}-linux-arm64.tar.bz2

    - name: Upload release
      run: |
        gh release create "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" -n "release from pipeline" -t "v${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}" || true
        gh release upload "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" "python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-win-x86_64:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ wait-build-all ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="win-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Download artefact
      uses: actions/download-artifact@v8
      with:
        name: python-${{env.BUILD_VERSION}}-win-x86_64.tar.bz2

    - name: Upload release
      run: |
        gh release create "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" -n "release from pipeline" -t "v${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}" || true
        gh release upload "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" "python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-win-arm64:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ wait-build-all ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="win-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Download artefact
      uses: actions/download-artifact@v8
      with:
        name: python-${{env.BUILD_VERSION}}-win-arm64.tar.bz2

    - name: Upload release
      run: |
        gh release create "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" -n "release from pipeline" -t "v${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}" || true
        gh release upload "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" "python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macos-x86_64:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ wait-build-all ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="macos-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Download artefact
      uses: actions/download-artifact@v8
      with:
        name: python-${{env.BUILD_VERSION}}-macos-x86_64.tar.bz2

    - name: Upload release
      run: |
        gh release create "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" -n "release from pipeline" -t "v${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}" || true
        gh release upload "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" "python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macos-arm64:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ wait-build-all ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="macos-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Download artefact
      uses: actions/download-artifact@v8
      with:
        name: python-${{env.BUILD_VERSION}}-macos-arm64.tar.bz2

    - name: Upload release
      run: |
        gh release create "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" -n "release from pipeline" -t "v${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}" || true
        gh release upload "v${{ env.BUILD_VERSION }}-${{env.BUILD_TARGET}}" "python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-all:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ release-linux-x86_64, release-linux-arm64, release-win-x86_64, release-win-arm64, release-macos-x86_64, release-macos-arm64 ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="macos-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Create manifest
      shell: bash
      run: |
        export MANIFEST_NAME="v${{ env.BUILD_VERSION }}.manifest.json"
        echo "MANIFEST_NAME=$MANIFEST_NAME" >> $GITHUB_ENV
        python3 package.py create-package-manifest > "$MANIFEST_NAME"

    - name: Upload release
      run: |
        gh release create "v${{ env.BUILD_VERSION }}-manifest.json" -n "release from pipeline" -t "v${{env.BUILD_VERSION}}-manifest.json" || true
        gh release upload "v${{ env.BUILD_VERSION }}-manifest.json" "$MANIFEST_NAME" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-scheduler:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ release-all ]

    steps:
    - name: Trigger build scheduler
      shell: bash
      run: |
        echo "implement tiggering..."
        echo "run id: ${{ github.run_id }}"
