name: Build python

on:
  push:
    branches: [ "main" ]
    tags:
    - 'v*'




jobs:
  wait-dependencies:
    runs-on: ubuntu-24.04
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Wait for dependencies
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        python3 package.py wait-dependencies


  build-python-linux-x86_64:
    runs-on: ubuntu-24.04
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Check out build support scripts
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        BUILD_TARGET="macos-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Install build requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential checkinstall libreadline-dev libgdbm-dev libssl-dev libsqlite3-dev tk-dev libncurses5-dev libffi-dev libreadline-dev libbz2-dev liblzma-dev zlib1g-dev git

    - name: Build python
      shell: bash
      run: |
        ./scripts/python/build.sh

    - name: Upload artefacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artefacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-python-linux-arm64:
    runs-on: ubuntu-24.04-arm
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Check out build support scripts
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        BUILD_TARGET="linux-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Install build requirements
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential checkinstall libreadline-dev libgdbm-dev libssl-dev libsqlite3-dev tk-dev libncurses5-dev libffi-dev libreadline-dev libbz2-dev liblzma-dev zlib1g-dev git

    - name: Build python
      shell: bash
      run: |
        ./scripts/python/build.sh

    - name: Upload artefacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artefacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-python-win-arm64:
    runs-on: windows-11-vs2026-arm
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Check out build support scripts
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        BUILD_TARGET="win-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Setup MSVC developer command prompt
      uses: ilammy/msvc-dev-cmd@v1
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    - name: Build python
      shell: bash
      run: |
        export WINDOWS_BUILD="arm64"
        export WINDOWS_PCPKG_TUPLE="arm64-windows"
        ./scripts/python/build.sh

    - name: Upload artefacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artefacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-python-win-x86_64:
    runs-on: windows-2025-vs2026
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Check out build support scripts
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        BUILD_TARGET="win-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Setup MSVC developer command prompt
      uses: ilammy/msvc-dev-cmd@v1
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    - name: Build python
      shell: bash
      run: |
        export WINDOWS_BUILD="x64"
        export WINDOWS_PCPKG_TUPLE="x64-windows"
        ./scripts/python/build.sh

    - name: Upload artefacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artefacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-python-macos-arm64:
    runs-on: macos-15
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Check out build support scripts
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        BUILD_TARGET="macos-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Install build requirements
      shell: bash
      run: |
        brew install openssl xz gdbm cmake wget pkg-config

    - name: Build python
      shell: bash
      run: |
        ./scripts/python/build.sh

    - name: Upload artefacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artefacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  build-python-macos-x86_64:
    runs-on: macos-15-intel
    needs: wait-dependencies
    environment: build

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Check out build support scripts
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        BUILD_TARGET="macos-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Install build requirements
      shell: bash
      run: |
        brew trust aws/tap
        brew install openssl xz gdbm cmake wget pkg-config

    - name: Build python
      shell: bash
      run: |
        ./scripts/python/build.sh

    - name: Upload artefacts
      uses: actions/upload-artifact@v7
      with:
        name: python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        path: artefacts/python-${{env.BUILD_VERSION}}-${{env.BUILD_TARGET}}.tar.bz2
        compression-level: 0
        archive: false


  all-build:
    runs-on: ubuntu-24.04
    environment: build
    needs:
      build-python-linux-arm64
      build-python-linux-x86_64
      build-python-win-arm64
      build-python-win-x86_64
      build-python-macos-arm64
      build-python-macos-x86_64

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Check out build support scripts
      shell: bash
      run: |
        export FROST_BUILDER_REPO_URL="${{ vars.FROST_BUILDER_REPO_URL }}"
        export FROST_BUILDER_REPO_USER="${{ vars.FROST_BUILDER_REPO_USER }}"
        export FROST_BUILDER_REPO_PREFIX="${{ vars.FROST_BUILDER_REPO_PREFIX }}"
        export FROST_BUILDER_REPO_SUPPORT="${{ vars.FROST_BUILDER_REPO_SUPPORT }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_REPO_URL}/${FROST_BUILDER_REPO_USER}/${FROST_BUILDER_REPO_SUPPORT}.git" .
        popd
        echo "Setting up target build variables"
        BUILD_VERSION=$( python3 package.py "version-combined" )
        BUILD_TARGET="macos-x86_64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: On all build
      shell: bash
      run: |
        echo "TOFO: all platforms are now build"
