name: Trigger scheduler

on:
  workflow_run:
    workflows: [ "release-all" ]
    types:
      - completed

jobs:
  trigger-scheduler:
    runs-on: ubuntu-slim
    environment: build
    # if: startsWith(github.ref, 'refs/tags/')
    needs: [ release-all ]

    steps:
    - name: Check out sources
      uses: actions/checkout@v7

    - name: Set up Python 3
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Setup package
      shell: bash
      run: |
        export FROST_BUILDER_PACKAGE_SOURCES="${{ vars.FROST_BUILDER_PACKAGE_SOURCES }}"
        export FROST_BUILDER_SUPPORT_SCRIPTS="${{ vars.FROST_BUILDER_SUPPORT_SCRIPTS }}"
        echo "Cloning build support library"
        mkdir -p frost_support 
        pushd frost_support
        git clone "${FROST_BUILDER_SUPPORT_SCRIPTS}" .
        popd
        echo "Setting up target build variables"
        export BUILD_VERSION=$( python3 package.py "version-combined" )
        export BUILD_TARGET="macos-arm64"
        echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
        echo "BUILD_TARGET=$BUILD_TARGET" >> $GITHUB_ENV

    - name: Trigger build scheduler
      shell: bash
      run: |
        echo "Trigger scheduler"
        gh workflow run trigger-from-package.yml --repo "${{ env.FROST_BUILDER_SCHEDULER_TASK }}" --ref "main" -f package="python" -f version="$BUILD_VERSION" -f runid="${{ github.run_id }}"
